export const brandOptions = [
  "Default",
  "Realme",
  "OnePlus",
  "Huawei",
  "Redmi",
  "Techno",
  "Samsung",
  "Iphone",
  "Vivo",
  "oppo",
  "poco",
  "infinix",
  "Ronin",
  "Faster",
  "Amb",
]; // Add other brands here
export const categoryOptions = [
  "General",
  "Cover",
  "Mobile",
  "Smart Watches",
  "Wireless Chargers",
  "Bluetooths",
]; // Add other categories here
